language: python
python:
  - 3.5
before_script:
 - chmod +x ./setup.py
before_install:
 - sudo apt-get install libboost-all-dev
 - sudo add-apt-repository ppa:george-edison55/cmake-3.x -y
 - sudo apt-get update
 - sudo apt-get install cmake
 - sudo apt-get install python-dev
 - sudo apt-get install libhdf5-dev
 - sudo apt-get install gfortran libopenblas-dev liblapack-dev
install:
  - pip install codecov
  - pip install tensorflow
  - pip install opencv-python
script:
  - ./setup.py test
after_success:
  - codecov
