language: python
python:
  - 3.5
before_script:
 - chmod +x ./setup.py
before_install:
 - sudo apt-get install libboost-all-dev
 - git clone https://github.com/davisking/dlib.git
 - cd dlib
 - mkdir build; cd build; cmake .. -DDLIB_USE_CUDA=0 -DUSE_AVX_INSTRUCTIONS=1; cmake --build .
 - cd ..
 - python setup.py install --yes USE_AVX_INSTRUCTIONS --no DLIB_USE_CUDA
install:
  - pip install -r requirements.txt
  - pip install codecov
script:
  - ./setup.py test
after_success:
  - codecov
