language: python
python:
  - 3.5
before_script:
 - chmod +x ./setup.py
# help python importing cv and/or cv2
- export PYTHONPATH=$PYTHONPATH:/usr/lib/pymodules/python3.5
install:
  - pip install codecov
script:
  - ./setup.py test
after_success:
  - codecov
