language: python
python:
  - 3.5
before_script:
 - chmod +x ./setup.py
before_install:
 - sudo apt-get install libboost-all-dev
 - sudo add-apt-repository ppa:george-edison55/cmake-3.x
 - sudo apt-get update
 - sudo apt-get install cmake
install:
  - pip install -r requirements.txt
  - pip install codecov
script:
  - ./setup.py test
after_success:
  - codecov
